bookReviewingSys/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    
    path('admin/', admin.site.urls),
    path('registration/', include('users.urls')),
    path('', include('homepage.urls')),
    path('', include('mainpage.urls')),
    path('managements/', include('admins.urls')),
]
# if settings.DEBUG:
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

books/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
  path('', login_required(views.BookListView.as_view()), name='book_list'),
  path('books/', login_required(views.BookListView.as_view()), name='book_list'),
  path('books/<int:pk>/', login_required(views.BookDetailView.as_view()), name='book_detail'),
  path('activities/', login_required(views.activities)),
  path('activities/<int:pk>/change/', login_required(views.activitiesChange)),
  path('activities/<int:pk>/delete/', login_required(views.activitiesDelete)),
  path('users/<int:pk>/', login_required(views.UserDetailView.as_view()), name="user_detail"),
  path('accounts/login/', views.accountsLogin),
  path('accounts/logout/', views.accountsLogout, name='logout'),
  path('accounts/signup/', views.accountsSignup, name='signup'),
]

components/books/urls.py
from django.urls import path

from .views import (
    CategoryCreateView,
    CategoryIndexView,
    CategoryUpdateView,
    CategoryDeleteView,
    BookCreateView,
    BookUpdateReadStatusView,
    BookToggleFavoriteView,
    BookIndexView,
    BookUpdateView,
    BookDeleteView,
    BookDetailView,
    CommentCreateView,
    ReviewCreateView
)

app_name = 'book'

urlpatterns = [
    path('category/create', CategoryCreateView.as_view(), name='category_create'),
    path('category', CategoryIndexView.as_view(), name='category_index'),
    path('category/<int:id>/edit', CategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:id>/del', CategoryDeleteView.as_view(), name='category_delete'),
    path('book/create', BookCreateView.as_view(), name='book_create'),
    path('book', BookIndexView.as_view(), name='book_index'),
    path('book/<int:id>/update-read-status', BookUpdateReadStatusView.as_view(), name='book_update_read_status'),
    path('book/<int:id>/toggle-favorite', BookToggleFavoriteView.as_view(), name='book_toggle_favorite'),
    path('book/<int:id>/edit', BookUpdateView.as_view(), name='book_update'),
    path('book/<int:id>/del', BookDeleteView.as_view(), name='book_delete'),
    path('book/<int:id>/detail', BookDetailView.as_view(), name='book_detail'),
    path('book/<int:id>/create-comment', CommentCreateView.as_view(), name='book_create_comment'),
    path('book/<int:id>/create-review', ReviewCreateView.as_view(), name='book_create_review'),
]

dpt01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('books.urls')),
    path('admin/', admin.site.urls),
]

pinky_book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('components.users.urls')),
    path('', include('components.books.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

books/forms.py
from django import forms
from .models import Activity

class LoginForm(forms.Form):
  username = forms.CharField(label='User name', max_length=100)
  password = forms.CharField(
    label='Password',
    max_length=100,
    widget=forms.PasswordInput()
  )

class SignupForm(forms.Form):
  username = forms.CharField(label='User name', max_length=100)
  email = forms.EmailField(label='Email', max_length=100)
  password = forms.CharField(
    label='Password',
    max_length=100,
    widget=forms.PasswordInput()
  )

class BookListSearchForm(forms.Form):
  user_id = forms.IntegerField(widget=forms.HiddenInput())
  is_search = forms.BooleanField(widget=forms.HiddenInput(), initial=True)

  reading = forms.BooleanField(required=False)
  readed = forms.BooleanField(required=False)
  favorite = forms.BooleanField(required=False)
  pending = forms.BooleanField(required=False)
  approve = forms.BooleanField(required=False)
  reject = forms.BooleanField(required=False)

  title__contains = forms.CharField(label='title', required=False)

  pub_date__gt = forms.DateField(
    label='pub_date_start',
    required=False,
    widget=forms.DateTimeInput
  )
  pub_date__lt = forms.DateField(
    label='pub_date_end',
    required=False,
    widget=forms.DateTimeInput
  )

class ActivityAdminForm(forms.ModelForm):
  status = forms.ChoiceField(
    widget=forms.Select(), choices=(Activity.BUY_STATUSES))

components/books/forms.py
from pprint import pprint

from django import forms
from .models import (
    Category,
    Book
)


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(CategoryCreateForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Category.objects.filter(name=name).exists():
            raise forms.ValidationError('Danh mục đã tồn tại')

        return name

    def save(self, commit=True):
        self.instance.user = self.user
        category = super(CategoryCreateForm, self).save(commit)

        return category


class CategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Category.objects.filter(name=name).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('Danh mục đã tồn tại')

        return name


class BookCreateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'name',
            'image',
            'description',
            'publish_date',
            'author',
            'number_page',
            'price',
            'category',
        ]

    def __init__(self, user, files, data):
        self.user = user
        super(BookCreateForm, self).__init__(data, files)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Book.objects.filter(name=name).exists():
            raise forms.ValidationError('Tên sách đã tồn tại')

        return name

    def save(self, commit=True):
        self.instance.user = self.user

        book = super(BookCreateForm, self).save(commit)

        return book


class BookUpdateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'name',
            'image',
            'description',
            'publish_date',
            'author',
            'number_page',
            'price',
            'category',
        ]

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Book.objects.filter(name=name).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('Tên sách đã tồn tại')

        return name

books/views.py
from django.shortcuts import render

# Create your views here.

books/views/accounts.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

from ..models import User
from ..forms import LoginForm, SignupForm

def accountsLogin(request):
  if request.method == 'POST':
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username=username, password=password)

    if user is not None:
      login(request, user)

    next_url = request.POST.get('next')

    if next_url is None: next_url = '/books'

    return redirect(next_url)
  else:
    return render(request, 'books/login.html',
      {'form': LoginForm(), 'next': request.GET.get('next')})

def accountsLogout(request):
  logout(request)
  return redirect('/books')

def accountsSignup(request):
  if request.user.is_authenticated:
    return redirect('/books')

  if request.method == 'POST':
    username = request.POST.get('username')
    email = request.POST.get('email')
    password = request.POST.get('password')

    user = User.objects.create_user(username, email, password)

    try:
      user.save()
    except Exception as e:
      return redirect('/accounts/signup')
    else:
      login(request, user)
      return redirect('/books')
  else:
    return render(request, 'books/signup.html', {'form': SignupForm()})

books/views/activities.py
from django.contrib.contenttypes.models import ContentType
from django.http import JsonResponse
from django.forms.models import model_to_dict

from ..models import Activity

def activities(request):
  user_id = request.POST.get('user_id') or request.user.id

  target_object_type = request.POST.get('target_object_type')
  if target_object_type == 'user':
    target_object_type_id = ContentType.objects.get(
      app_label='auth', model='user').id
  else:
    target_object_type_id = ContentType.objects.get(
      app_label='books', model=target_object_type).id

  target_object_id = request.POST.get('target_object_id')
  content = request.POST.get('content')
  status = request.POST.get('status')
  action_type = request.POST.get('action_type')

  activity = Activity(
    user_id=user_id,
    target_object_id=target_object_id,
    target_object_type_id=target_object_type_id,
    action_type=action_type,
    content=content,
    status=status,
  )
  activity.save()

  return JsonResponse({ **model_to_dict(activity), 'status_text': activity.status_text() })

def activitiesChange(request, pk):
  activity = Activity.objects.get(pk=pk)

  activity.content = request.POST.get('content') or activity.content
  activity.status = request.POST.get('status') or activity.status
  activity.action_type = request.POST.get('action_type') or activity.action_type
  activity.save()

  return JsonResponse({ **model_to_dict(activity), 'status_text': activity.status_text() })

def activitiesDelete(request, pk):
  activity = Activity.objects.get(pk=pk)

  activityChildren = Activity.objects.filter(
    target_object_id=activity.id,
    target_object_type_id=ContentType.objects.get(app_label='books', model='activity').id,
  )

  if activityChildren is not None: activityChildren.delete()

  activity.delete()

  return JsonResponse({})

books/views/books.py
from django.views.generic import ListView, detail
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType

from ..models import Book, Activity
from ..forms import BookListSearchForm

class BookListView(ListView):
  paginate_by = 8
  model = Book
  form_class = BookListSearchForm

  def get_queryset(self):
    filter_params = dict(self.request.GET)
    user_id = filter_params.get('user_id', [None])[0]
    if user_id is None or user_id == '': user_id = self.request.user.id
    activities = Activity.objects.filter(
        user_id=user_id,
        target_object_type_id=ContentType.objects.get(
          app_label='books', model='book').id
      )
    query_or = Q()

    if filter_params.get('reading', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.READ, status=Activity.READING).values('target_object_id'))

    if filter_params.get('readed', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.READ, status=Activity.READED).values('target_object_id'))

    if filter_params.get('favorite', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.FAVORITE).values('target_object_id'))

    if filter_params.get('pending', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.BUY, status=Activity.BUY_PENDING).values('target_object_id'))

    if filter_params.get('approve', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.BUY, status=Activity.BUY_APPROVE).values('target_object_id'))

    if filter_params.get('reject', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.BUY, status=Activity.BUY_REJECT).values('target_object_id'))

    query_and = Q()

    for field in ['title__contains', 'pub_date__lt', 'pub_date__gt']:
      field_filter = filter_params.get(field, [None])[0]
      if field_filter: query_and &= Q(**{field: field_filter})

    return Book.objects.filter(Q(query_or) & Q(query_and))

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)

    context['form'] = self.form_class(self.request.GET)
    context['newest_book_public'] = Book.objects.all().order_by('-pub_date')[0]
    context['newest_review'] = Activity.objects.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.COMMENT,)[0]
    context['is_search'] = self.request.GET.get('is_search')
    context['page'] = self.request.GET.get('page')

    return context

class BookDetailView(detail.DetailView):
  model = Book

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)

    user = self.request.user
    book = kwargs['object']

    context['read'] = book.activities().filter(
      user_id=user.id, action_type=Activity.READ).first()
    context['favorite'] = book.activities().filter(
      user_id=user.id, action_type=Activity.FAVORITE).first()
    context['buy'] = book.activities().filter(
      user_id=user.id, action_type=Activity.BUY).first()
    context['rate'] = book.activities().filter(
      user_id=user.id, action_type=Activity.RATE).first()

    return context

books/views/users.py
from django.views.generic import detail
from django.contrib.contenttypes.models import ContentType

from ..models import User, Book, Activity

class UserDetailView(detail.DetailView):
  model = User
  template_name = 'books/user_detail.html'

  def get_context_data(self, **kwargs):
    MAX_EXTRA_RECORD = 3

    context = super().get_context_data(**kwargs)

    current_user = self.request.user
    user = kwargs['object']

    activities = Activity.objects.filter(user_id=user.id)

    context['follow_act'] = Activity.objects.filter(
      user_id=current_user.id,
      target_object_id=user.id,
      target_object_type_id=ContentType.objects.get(
        app_label='auth', model='user').id,
      action_type=Activity.FOLLOW).first()

    following = Activity.objects.filter(
      target_object_id=user.id,
      target_object_type_id=ContentType.objects.get(
        app_label='auth', model='user').id,
      action_type=Activity.FOLLOW)
    context['following_count'] = following.count()
    context['following_users'] = User.objects.filter(
      id__in=[a.user_id for a in following[:MAX_EXTRA_RECORD]])

    followed = Activity.objects.filter(
      user_id=user.id,
      target_object_type_id=ContentType.objects.get(
        app_label='auth', model='user').id,
      action_type=Activity.FOLLOW)
    context['followed_count'] = followed.count()
    context['followed_users'] = User.objects.filter(
      id__in=[a.target_object_id for a in followed[:MAX_EXTRA_RECORD]])

    reading = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.READ,
      status=Activity.READING)

    context['reading_count'] = reading.count()
    context['reading_books'] = Book.objects.filter(
      id__in=[a.target_object_id for a in reading[:MAX_EXTRA_RECORD]])

    readed = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.READ,
      status=Activity.READED)

    context['readed_count'] = readed.count()
    context['readed_books'] = Book.objects.filter(
      id__in=[a.target_object_id for a in readed[:MAX_EXTRA_RECORD]])

    favorite = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.FAVORITE)
    context['favorite_count'] = favorite.count()
    context['favorite_books'] = Book.objects.filter(
      id__in=[a.target_object_id for a in favorite[:MAX_EXTRA_RECORD]])

    review = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.COMMENT)

    context['review_count'] = review.count()
    context['reviews'] = review[:MAX_EXTRA_RECORD]

    context['activities'] = activities.filter(
      action_type__in=[Activity.COMMENT, Activity.READ, Activity.FAVORITE,
        Activity.FOLLOW, Activity.BUY]).exclude(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='activity').id)

    return context

components/books/templates/book_index.html
{% extends 'layouts/master.html' %}
{% load static %}
{% load humanize %}
{% load user_extras %}

{% block content %}
  <div class="page-content-wrapper">
    <div class="page-content">
      <div class="page-bar">
        <ul class="page-breadcrumb">
          <li>
            <a href="javascript:void(0)">Thư viện sách</a>
          </li>
        </ul>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% include 'partials/alert_message.html' %}
          <div class="portlet box green-haze">
            <div class="portlet-title">
              <div class="caption">
                {{ title }}
              </div>
              <div class="actions">
                {% if user.role == 1 %}
                  <a href="{% url 'book:book_create' %}" id="sample_editable_1_new" class="btn green">
                    <i class="fa fa-plus"></i>
                    Thêm mới
                  </a>
                {% endif %}
              </div>
            </div>
            <div class="portlet-body">
              <table class="table table-striped table-bordered table-hover" id="sample_3">
                <thead>
                <tr>
                  <th>Hình ảnh</th>
                  <th>Tên sách</th>
                  <th>Tác giả</th>
                  <th>Giá</th>
                  <th>Số trang</th>
                  <th>NXB</th>
                  <th>Xếp hạng</th>
                  <th>Trạng thái</th>
                  <th class="text-center">Yêu thích</th>
                  <th>Hành động</th>
                  <th class="hide">Detail</th>
                </tr>
                </thead>
                <tbody>
                {% for book in books %}
                  <tr>
                    <td class="fashion-fix-image-product">
                      {% if book.image %}
                        <img src="/media/{{ book.image }}" class="img-responsive">
                      {% endif %}
                    </td>
                    <td>
                      <a href="{% url 'book:book_detail' id=book.id %}">
                        {{ book.name }}
                      </a>
                    </td>
                    <td>{{ book.author|default_if_none:'' }}</td>
                    <td>{{ book.price|default_if_none:0|intcomma }}đ</td>
                    <td>{{ book.number_page|default_if_none:1 }}</td>
                    <td>{{ book.publish_date|default_if_none:'' }}</td>
                    <td class="text-center">
                      <div class="rateit pinky-cursor-disable" data-rateit-value="{{ book.rating }}" data-rateit-ispreset="true" data-rateit-readonly="true"></div>
                      <div>({{ book.total_reviews }} đánh giá)</div>
                    </td>
                    <td>
                      <span class="hide">{{ book.read_status }}</span>
                      <select
                        name="read_status"
                        class="form-control bs-select fashion-change-status"
                        data-url="{% url 'book:book_update_read_status' id=book.id %}"
                        data-message="Cập nhật trạng thái thành công"
                      >
                        {% for key,item in status.items %}
                          <option value="{{ key }}" {% if book.read_status == key %} selected {% endif %}>{{ item }}</option>
                        {% endfor %}
                      </select>
                    </td>
                    <td class="text-center">
                      <span class="hide">{{ book.is_favorite }}</span>
                      <i
                        class="fix-feature fashion-toggle {{ icon_class|get_item_dictionary:book.is_favorite }}"
                        data-url="{% url 'book:book_toggle_favorite' id=book.id %}"
                        data-icon-class-create="{{ icon_class.1 }}"
                        data-icon-class-delete="{{ icon_class.0 }}"
                        data-message-create="Đã thêm vào danh sách yêu thích"
                        data-message-delete="Đã loại bỏ khỏi danh sách yêu thích"
                      >
                      </i>
                    </td>
                    <td>
                      {% if user.role == 1 %}
                        <a href="{% url 'book:book_update' id=book.id %}" class="btn default btn-xs purple">
                          <i class="fa fa-edit"></i>
                          Sửa
                        </a>
                        <span
                          data-url="{% url 'book:book_delete' id=book.id %}"
                          data-message="Xoá thành công"
                          class="btn default btn-xs black fashion-soft-delete-item"
                          data-original-title="Bạn có chắc không"
                          data-btn-ok-label="Đồng ý"
                          data-btn-cancel-label="Không"
                          data-toggle="confirmation"
                          data-placement="left"
                          data-popout="true"
                          data-singleton="true"
                          data-btn-ok-class="btn-success"
                          data-btn-cancel-class="btn-danger"
                        >
                          <i class="fa fa-trash-o"></i>
                          Xoá
                        </span>
                      {% endif %}
                      <a href="{% url 'book:book_detail' id=book.id %}" class="btn default btn-xs red-stripe">
                        Chi tiết
                      </a>
                    </td>
                    <td class="display-none">
                      {{ book.description|default_if_none:'' }}
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script src="{% static 'assets/global/plugins/rateit/src/jquery.rateit.js' %}"></script>
  <script>
      jQuery(document).ready(function () {
          TableAdvanced.init();
      });
  </script>
{% endblock %}

components/books/templates/category_create.html
{% extends 'layouts/master.html' %}
{% load static %}

{% block content %}
  <div class="page-content-wrapper">
    <div class="page-content">
      <div class="page-bar">
        <ul class="page-breadcrumb">
          <li>
            <a href="javascript:void(0)">Danh mục</a>
            <i class="fa fa-angle-right"></i>
          </li>
          <li>
            <a href="javascript:void(0)">Thêm mới</a>
          </li>
        </ul>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="portlet box green-haze">
            <div class="portlet-title">
              <div class="caption">Thêm mới danh mục</div>
            </div>
            <div class="portlet-body form">
              <form method="POST" action="{% url 'book:category_create' %}" accept-charset="UTF-8" class="form-horizontal form-row-seperated">
                {% csrf_token %}
                <div class="form-body">
                  <div class="form-group {% if 'name' in form.errors %} has-error {% endif %}">
                    <label for="name" class="control-label col-md-3 required">Tên</label>
                    <div class="col-md-9">
                      <input class="form-control fashion-name" name="name" type="text" id="name" value="{{ request.POST.name }}">
                      {% for error in form.errors.name %}
                        <span class="help-block help-block-error">
                            {{ error|escape }}
                        </span>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                <div class="form-actions">
                  <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                      <input class="btn green" type="submit" value="Thêm">
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
      jQuery(document).ready(function () {
          FormSamples.init();
      });
  </script>
{% endblock %}

components/books/templates/category_index.html
{% extends 'layouts/master.html' %}
{% load static %}

{% block content %}
  <div class="page-content-wrapper">
    <div class="page-content">
      <div class="page-bar">
        <ul class="page-breadcrumb">
          <li>
            <a href="javascript:void(0)">Danh mục</a>
            <i class="fa fa-angle-right"></i>
          </li>
          <li>
            <a href="javascript:void(0)">Danh sách</a>
          </li>
        </ul>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% include 'partials/alert_message.html' %}
          <div class="portlet box green-haze">
            <div class="portlet-title">
              <div class="caption">
                Tất cả danh mục
              </div>
              <div class="actions">
                {% if user.role == 1 %}
                  <a href="{% url 'book:category_create' %}" id="sample_editable_1_new" class="btn green">
                    <i class="fa fa-plus"></i>
                    Thêm mới
                  </a>
                {% endif %}
              </div>
            </div>
            <div class="portlet-body">
              <table class="table table-striped table-bordered table-hover" id="sample_1">
                <thead>
                <tr>
                  <th>STT</th>
                  <th>Tên</th>
                  <th>Thời gian tạo</th>
                  <th>Hành động</th>
                </tr>
                </thead>
                <tbody>
                {% for category in categories %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ category.name }}</td>
                    <td>{{ category.created_at|date:'Y-m-d' }}</td>
                    <td>
                      {% if user.role == 1 %}
                        <a href="{% url 'book:category_update' id=category.id %}" class="btn default btn-xs purple">
                          <i class="fa fa-edit"></i>
                          Sửa
                        </a>
                        <span
                          data-url="{% url 'book:category_delete' id=category.id %}"
                          data-message="Xoá thành công"
                          class="btn default btn-xs black fashion-soft-delete-item"
                          data-original-title="Bạn có chắc không"
                          data-btn-ok-label="Đồng ý"
                          data-btn-cancel-label="Không"
                          data-toggle="confirmation"
                          data-placement="left"
                          data-popout="true"
                          data-singleton="true"
                          data-btn-ok-class="btn-success"
                          data-btn-cancel-class="btn-danger"
                        >
                          <i class="fa fa-trash-o"></i>
                          Xoá
                        </span>
                      {% endif %}
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
      jQuery(document).ready(function () {
          TableAdvanced.init();
      });
  </script>
{% endblock %}

components/books/templates/category_update.html
{% extends 'layouts/master.html' %}
{% load static %}

{% block content %}
  <div class="page-content-wrapper">
    <div class="page-content">
      <div class="page-bar">
        <ul class="page-breadcrumb">
          <li>
            <a href="javascript:void(0)">Danh mục</a>
            <i class="fa fa-angle-right"></i>
          </li>
          <li>
            <a href="javascript:void(0)">Chỉnh sửa</a>
          </li>
        </ul>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="portlet box green-haze">
            <div class="portlet-title">
              <div class="caption">Chỉnh sửa danh mục</div>
            </div>
            <div class="portlet-body form">
              <form method="POST" action="{% url 'book:category_update' id=category.id %}" accept-charset="UTF-8" class="form-horizontal form-row-seperated">
                {% csrf_token %}
                <div class="form-body">
                  <div class="form-group {% if 'name' in form.errors %} has-error {% endif %}">
                    <label for="name" class="control-label col-md-3 required">Tên</label>
                    <div class="col-md-9">
                      <input class="form-control fashion-name" name="name" type="text" id="name" value="{{ request.POST.name|default:category.name }}">
                      {% for error in form.errors.name %}
                        <span class="help-block help-block-error">
                            {{ error|escape }}
                        </span>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                <div class="form-actions">
                  <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                      <input class="btn green" type="submit" value="Cập nhật">
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
      jQuery(document).ready(function () {
          FormSamples.init();
      });
  </script>
{% endblock %}