bookReviewingSys/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    
    path('admin/', admin.site.urls),
    path('registration/', include('users.urls')),
    path('', include('homepage.urls')),
    path('', include('mainpage.urls')),
    path('managements/', include('admins.urls')),
]
# if settings.DEBUG:
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

books/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
  path('', login_required(views.BookListView.as_view()), name='book_list'),
  path('books/', login_required(views.BookListView.as_view()), name='book_list'),
  path('books/<int:pk>/', login_required(views.BookDetailView.as_view()), name='book_detail'),
  path('activities/', login_required(views.activities)),
  path('activities/<int:pk>/change/', login_required(views.activitiesChange)),
  path('activities/<int:pk>/delete/', login_required(views.activitiesDelete)),
  path('users/<int:pk>/', login_required(views.UserDetailView.as_view()), name="user_detail"),
  path('accounts/login/', views.accountsLogin),
  path('accounts/logout/', views.accountsLogout, name='logout'),
  path('accounts/signup/', views.accountsSignup, name='signup'),
]

components/books/urls.py
from django.urls import path

from .views import (
    CategoryCreateView,
    CategoryIndexView,
    CategoryUpdateView,
    CategoryDeleteView,
    BookCreateView,
    BookUpdateReadStatusView,
    BookToggleFavoriteView,
    BookIndexView,
    BookUpdateView,
    BookDeleteView,
    BookDetailView,
    CommentCreateView,
    ReviewCreateView
)

app_name = 'book'

urlpatterns = [
    path('category/create', CategoryCreateView.as_view(), name='category_create'),
    path('category', CategoryIndexView.as_view(), name='category_index'),
    path('category/<int:id>/edit', CategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:id>/del', CategoryDeleteView.as_view(), name='category_delete'),
    path('book/create', BookCreateView.as_view(), name='book_create'),
    path('book', BookIndexView.as_view(), name='book_index'),
    path('book/<int:id>/update-read-status', BookUpdateReadStatusView.as_view(), name='book_update_read_status'),
    path('book/<int:id>/toggle-favorite', BookToggleFavoriteView.as_view(), name='book_toggle_favorite'),
    path('book/<int:id>/edit', BookUpdateView.as_view(), name='book_update'),
    path('book/<int:id>/del', BookDeleteView.as_view(), name='book_delete'),
    path('book/<int:id>/detail', BookDetailView.as_view(), name='book_detail'),
    path('book/<int:id>/create-comment', CommentCreateView.as_view(), name='book_create_comment'),
    path('book/<int:id>/create-review', ReviewCreateView.as_view(), name='book_create_review'),
]

components/users/urls.py
from django.urls import path

from .views import (
    UserLoginView,
    UserRegisterView,
    UserLogoutView,
    UserTimelineView,
    UserMyProfileView,
    MemberIndexView,
    MemberToggleFollowView,
    RequestCreateView,
    MyRequestView,
    RequestUpdateView,
    RequestDeleteView,
    RequestIndexView,
    RequestChangeStatusView
)

app_name = 'user'

urlpatterns = [
    path('login', UserLoginView.as_view(), name='login'),
    path('register', UserRegisterView.as_view(), name='register'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('', UserTimelineView.as_view(), name='timeline'),
    path('my-profile', UserMyProfileView.as_view(), name='my_profile'),
    path('member', MemberIndexView.as_view(), name='member_index'),
    path('member/<int:following_id>/toggle-follow', MemberToggleFollowView.as_view(), name='member_toggle_follow'),
    path('request/create', RequestCreateView.as_view(), name='request_create'),
    path('request/my-request', MyRequestView.as_view(), name='my_request'),
    path('request/<int:id>/edit', RequestUpdateView.as_view(), name='request_update'),
    path('request/<int:id>/del', RequestDeleteView.as_view(), name='request_delete'),
    path('request/', RequestIndexView.as_view(), name='request_index'),
    path('request/<int:id>/change-status', RequestChangeStatusView.as_view(), name='request_change_status'),
]

dpt01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('books.urls')),
    path('admin/', admin.site.urls),
]

pinky_book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('components.users.urls')),
    path('', include('components.books.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/layouts/footer.html
<div class="page-footer">
  <div class="page-footer-inner">
    2020 &copy; Pinky Book
  </div>
  <div class="scroll-to-top">
    <i class="icon-arrow-up"></i>
  </div>
</div>

templates/layouts/header.html
{% load static %}

<div class="page-header -i navbar navbar-fixed-top">
  <div class="page-header-inner">
    <div class="page-logo">
      <a href="{% url 'user:timeline' %}">
        <img src="{% static 'img/logo.png' %}" alt="logo" class="logo-default"/>
      </a>
      <div class="menu-toggler sidebar-toggler hide">
      </div>
    </div>
    <a href="javascript:void(0)" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
    </a>
    <div class="top-menu">
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown dropdown-user">
          <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
            <img alt="{{ user.username }}" class="img-circle" src="{% static 'img/avatar-no.png' %}"/>
            <span class="username username-hide-on-mobile">{{ user.username }}</span>
            <i class="fa fa-angle-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-default">
            <li>
              <a href="{% url 'user:my_profile' %}">
                <i class="icon-user"></i>
                Thông tin của tôi
              </a>
            </li>
            <li>
              <a href="{% url 'user:logout' %}">
                <i class="fa fa-sign-out"></i>
                Đăng xuất
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="clearfix"></div>

templates/layouts/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Pinky Book</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="csrf-token" content="{{ csrf_token }}">

    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}"/>
    {% include './style.html' %}
    {% block style %}{% endblock %}
</head>
<body class="page-header-fixed page-sidebar-fixed">
    {% include './header.html' %}
    <div class="page-container">
        {% include './sidebar.html' %}
        {% block content %}{% endblock %}
    </div>
    {% include './footer.html' %}
    {% include './script.html' %}
    {% block script %}{% endblock %}
</body>
</html>

templates/layouts/script.html
{% load static %}

<script src="{% static 'assets/global/plugins/respond.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/excanvas.min.js' %}"></script>

<script src="{% static 'assets/global/plugins/jquery.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/jquery-migrate.min.js' %}"></script>

<script src="{% static 'assets/global/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/jquery.blockui.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/jquery.cokie.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/uniform/jquery.uniform.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js' %}"></script>

<script src="{% static 'assets/global/plugins/bootstrap-select/bootstrap-select.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/select2/select2.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/jquery-multi-select/js/jquery.multi-select.js' %}"></script>
<script src="{% static 'assets/admin/pages/scripts/form-samples.js' %}"></script>
<script src="{% static 'assets/global/plugins/ckeditor/ckeditor.js' %}"></script>

<script src="{% static 'assets/global/plugins/datatables/media/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/datatables/extensions/ColReorder/js/dataTables.colReorder.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/datatables/extensions/Scroller/js/dataTables.scroller.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'assets/admin/pages/scripts/table-advanced.js' %}"></script>
<script src="{% static 'assets/admin/pages/scripts/table-managed.js' %}"></script>

<script src="{% static 'assets/global/plugins/fuelux/js/spinner.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js' %}"></script>
<script src="{% static 'assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/jquery.input-ip-address-control-1.0.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/bootstrap-pwstrength/pwstrength-bootstrap.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/jquery-tags-input/jquery.tagsinput.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/bootstrap-touchspin/bootstrap.touchspin.js' %}"></script>
<script src="{% static 'assets/global/plugins/typeahead/handlebars.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/typeahead/typeahead.bundle.min.js' %}"></script>

<script src="{% static 'assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js' %}"></script>

<script src="{% static 'assets/global/plugins/bootstrap-growl/jquery.bootstrap-growl.min.js' %}"></script>
<script src="{% static 'assets/admin/pages/scripts/ui-bootstrap-growl.js' %}"></script>

<script src="{% static 'assets/global/plugins/jquery-nestable/jquery.nestable.js' %}"></script>

<script src="{% static 'assets/global/scripts/metronic.js' %}"></script>
<script src="{% static 'assets/admin/layout/scripts/layout.js' %}"></script>
<script src="{% static 'assets/admin/layout/scripts/demo.js' %}"></script>

<script src="{% static 'assets/admin/pages/scripts/ui-confirmations.js' %}"></script>

<script src="{% static 'assets/admin/pages/scripts/components-dropdowns.js' %}"></script>
<script src="{% static 'assets/admin/pages/scripts/components-form-tools.js' %}"></script>

<script src="{% static 'assets/admin/app.js' %}"></script>
<script>
    jQuery(document).ready(function () {
        Metronic.init();
        Layout.init();
        Demo.init();
        UIBootstrapGrowl.init();
    });
</script>

templates/layouts/sidebar.html
<div class="page-sidebar-wrapper">
  <div class="page-sidebar navbar-collapse collapse">
    <ul class="page-sidebar-menu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
      <li class="sidebar-toggler-wrapper">
        <div class="sidebar-toggler">
        </div>
      </li>
      <li class="margin-top-15 {% if 'timeline' == request.resolver_match.url_name %}active{% endif %}">
        <a href="{% url 'user:timeline' %}">
          <i class="icon-paper-plane"></i>
          <span class="title">Dòng thời gian</span>
          {% if 'timeline' == request.resolver_match.url_name %}
            <span class="selected"></span>
          {% endif %}
        </a>
      </li>
      {% if user.role == 1 %}
        <li class="{% if '/category' in request.path %}active{% endif %}">
          <a href="javascript:void(0);">
            <i class="fa fa-sliders"></i>
            <span class="title">Danh mục sách</span>
            {% if '/category' in request.path %}
              <span class="selected"></span>
            {% endif %}
            <span class="arrow {% if '/category' in request.path %}open{% endif %}">
                    </span>
          </a>
          <ul class="sub-menu">

            <li class="{% if 'category_create' == request.resolver_match.url_name %}active{% endif %}">
              <a href="{% url 'book:category_create' %}">
                <i class="fa fa-plus"></i>
                Thêm mới
              </a>
            </li>
            <li class="{% if 'category_index' == request.resolver_match.url_name %}active{% endif %}">
              <a href="{% url 'book:category_index' %}">
                <i class="fa fa-list-ul"></i>
                Danh sách
              </a>
            </li>
          </ul>
        </li>
      {% endif %}
      <li class="{% if '/book' in request.path %}active{% endif %}">
        <a href="javascript:void(0);">
          <i class="fa fa-book"></i>
          <span class="title">Thư viện sách</span>
          {% if '/book' in request.path %}
            <span class="selected"></span>
          {% endif %}
          <span class="arrow {% if '/book' in request.path %}open{% endif %}">
                    </span>
        </a>
        <ul class="sub-menu">
          {% if user.role == 1 %}
            <li class="{% if 'book_create' == request.resolver_match.url_name %}active{% endif %}">
              <a href="{% url 'book:book_create' %}">
                <i class="fa fa-plus"></i>
                Thêm mới
              </a>
            </li>
          {% endif %}
          <li class="{% if 'book_index' == request.resolver_match.url_name and not request.GET.filter_sidebar %}active{% endif %}">
            <a href="{% url 'book:book_index' %}">
              <i class="fa fa-list-ul"></i>
              Tất cả sách
            </a>
          </li>
          <li class="{% if request.GET.favorite == '1' and request.GET.filter_sidebar %}active{% endif %}">
            <a href="{% url 'book:book_index' %}?filter_sidebar=1&favorite=1">
              <i class="fa fa-heart"></i>
              Sách yêu thích
            </a>
          </li>
          <li class="{% if request.GET.read_status == '1' and request.GET.filter_sidebar %}active{% endif %}">
            <a href="{% url 'book:book_index' %}?filter_sidebar=1&read_status=1">
              <i class="fa fa-bookmark-o"></i>
              Sách đang đọc
            </a>
          </li>
          <li class="{% if request.GET.read_status == '2' and request.GET.filter_sidebar %}active{% endif %}">
            <a href="{% url 'book:book_index' %}?filter_sidebar=1&read_status=2">
              <i class="fa fa-bookmark"></i>
              Sách đã đọc
            </a>
          </li>
        </ul>
      </li>
      <li class="{% if '/request' in request.path %}active{% endif %}">
        <a href="javascript:void(0);">
          <i class="fa fa-th"></i>
          <span class="title">
            Quản lý yêu cầu
          </span>
          {% if '/request' in request.path %}
            <span class="selected"></span>
          {% endif %}
          <span class="arrow {% if '/request' in request.path %}open{% endif %}">
              </span>
        </a>
        <ul class="sub-menu">
          <li class="{% if 'request_create' == request.resolver_match.url_name %}active{% endif %}">
            <a href="{% url 'user:request_create' %}">
              <i class="fa fa-plus"></i>
              Thêm mới yêu cầu
            </a>
          </li>
          <li class="{% if 'my_request' == request.resolver_match.url_name %}active{% endif %}">
            <a href="{% url 'user:my_request' %}">
              <i class="icon-user"></i>
              Yêu cầu của tôi
            </a>
          </li>
          {% if user.role == 1 %}
            <li class="{% if 'request_index' == request.resolver_match.url_name %}active{% endif %}">
              <a href="{% url 'user:request_index' %}">
                <i class="fa fa-list-ul"></i>
                Danh sách yêu cầu
              </a>
            </li>
          {% endif %}
        </ul>
      </li>
      <li class="{% if '/member' in request.path %}active{% endif %}">
        <a href="javascript:void(0);">
          <i class="icon-users"></i>
          <span class="title">Thành viên</span>
          {% if '/member' in request.path %}
            <span class="selected"></span>
          {% endif %}
          <span class="arrow {% if '/member' in request.path %}open{% endif %}">
          </span>
        </a>
        <ul class="sub-menu">
          <li class="{% if 'member_index' == request.resolver_match.url_name and not request.GET.filter_sidebar %}active{% endif %}">
            <a href="{% url 'user:member_index' %}">
              <i class="fa fa-list-ul"></i>
              Tất cả thành viên
            </a>
          </li>
          <li class="{% if request.GET.following == '1' and request.GET.filter_sidebar %}active{% endif %}">
            <a href="{% url 'user:member_index' %}?filter_sidebar=1&following=1">
              <i class="fa fa-user-md"></i>
              Đang theo dõi
            </a>
          </li>
          <li class="{% if request.GET.follower == '1' and request.GET.filter_sidebar %}active{% endif %}">
            <a href="{% url 'user:member_index' %}?filter_sidebar=1&follower=1">
              <i class="fa fa-users"></i>
              Người theo dõi
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>

templates/layouts/style.html
{% load static %}

<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all">
<link rel="stylesheet" href="{% static 'assets/global/plugins/font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/global/plugins/simple-line-icons/simple-line-icons.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/global/plugins/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/global/plugins/uniform/css/uniform.default.css' %}">
<link rel="stylesheet" href="{% static 'assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/global/plugins/datatables/extensions/Scroller/css/dataTables.scroller.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/global/plugins/datatables/extensions/ColReorder/css/dataTables.colReorder.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css' %}">

<link rel="stylesheet" href="{% static 'assets/global/plugins/bootstrap-select/bootstrap-select.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/global/plugins/select2/select2.css' %}">
<link rel="stylesheet" href="{% static 'assets/global/plugins/jquery-multi-select/css/multi-select.css' %}">

<link rel="stylesheet" href="{% static 'assets/global/plugins/jquery-nestable/jquery.nestable.css' %}">
<link rel="stylesheet" href="{% static 'assets/global/plugins/rateit/src/rateit.css' %}">

<link rel="stylesheet" href="{% static 'assets/global/css/components.css' %}">
<link rel="stylesheet" href="{% static 'assets/global/css/plugins.css' %}">
<link rel="stylesheet" href="{% static 'assets/admin/layout/css/layout.css' %}">
<link rel="stylesheet" href="{% static 'assets/admin/layout/css/themes/darkblue.css' %}">
<link rel="stylesheet" href="{% static 'assets/admin/layout/css/custom.css' %}">

<link rel="stylesheet" href="{% static 'assets/admin/app.css' %}">