bookReviewingSys/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    
    path('admin/', admin.site.urls),
    path('registration/', include('users.urls')),
    path('', include('homepage.urls')),
    path('', include('mainpage.urls')),
    path('managements/', include('admins.urls')),
]
# if settings.DEBUG:
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

books/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
  path('', login_required(views.BookListView.as_view()), name='book_list'),
  path('books/', login_required(views.BookListView.as_view()), name='book_list'),
  path('books/<int:pk>/', login_required(views.BookDetailView.as_view()), name='book_detail'),
  path('activities/', login_required(views.activities)),
  path('activities/<int:pk>/change/', login_required(views.activitiesChange)),
  path('activities/<int:pk>/delete/', login_required(views.activitiesDelete)),
  path('users/<int:pk>/', login_required(views.UserDetailView.as_view()), name="user_detail"),
  path('accounts/login/', views.accountsLogin),
  path('accounts/logout/', views.accountsLogout, name='logout'),
  path('accounts/signup/', views.accountsSignup, name='signup'),
]

dpt01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('books.urls')),
    path('admin/', admin.site.urls),
]

pinky_book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('components.users.urls')),
    path('', include('components.books.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

books/forms.py
from django import forms
from .models import Activity

class LoginForm(forms.Form):
  username = forms.CharField(label='User name', max_length=100)
  password = forms.CharField(
    label='Password',
    max_length=100,
    widget=forms.PasswordInput()
  )

class SignupForm(forms.Form):
  username = forms.CharField(label='User name', max_length=100)
  email = forms.EmailField(label='Email', max_length=100)
  password = forms.CharField(
    label='Password',
    max_length=100,
    widget=forms.PasswordInput()
  )

class BookListSearchForm(forms.Form):
  user_id = forms.IntegerField(widget=forms.HiddenInput())
  is_search = forms.BooleanField(widget=forms.HiddenInput(), initial=True)

  reading = forms.BooleanField(required=False)
  readed = forms.BooleanField(required=False)
  favorite = forms.BooleanField(required=False)
  pending = forms.BooleanField(required=False)
  approve = forms.BooleanField(required=False)
  reject = forms.BooleanField(required=False)

  title__contains = forms.CharField(label='title', required=False)

  pub_date__gt = forms.DateField(
    label='pub_date_start',
    required=False,
    widget=forms.DateTimeInput
  )
  pub_date__lt = forms.DateField(
    label='pub_date_end',
    required=False,
    widget=forms.DateTimeInput
  )

class ActivityAdminForm(forms.ModelForm):
  status = forms.ChoiceField(
    widget=forms.Select(), choices=(Activity.BUY_STATUSES))

components/books/forms.py
from pprint import pprint

from django import forms
from .models import (
    Category,
    Book
)


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(CategoryCreateForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Category.objects.filter(name=name).exists():
            raise forms.ValidationError('Danh mục đã tồn tại')

        return name

    def save(self, commit=True):
        self.instance.user = self.user
        category = super(CategoryCreateForm, self).save(commit)

        return category


class CategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Category.objects.filter(name=name).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('Danh mục đã tồn tại')

        return name


class BookCreateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'name',
            'image',
            'description',
            'publish_date',
            'author',
            'number_page',
            'price',
            'category',
        ]

    def __init__(self, user, files, data):
        self.user = user
        super(BookCreateForm, self).__init__(data, files)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Book.objects.filter(name=name).exists():
            raise forms.ValidationError('Tên sách đã tồn tại')

        return name

    def save(self, commit=True):
        self.instance.user = self.user

        book = super(BookCreateForm, self).save(commit)

        return book


class BookUpdateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'name',
            'image',
            'description',
            'publish_date',
            'author',
            'number_page',
            'price',
            'category',
        ]

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Book.objects.filter(name=name).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('Tên sách đã tồn tại')

        return name

books/views.py
from django.shortcuts import render

# Create your views here.

books/views/accounts.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

from ..models import User
from ..forms import LoginForm, SignupForm

def accountsLogin(request):
  if request.method == 'POST':
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username=username, password=password)

    if user is not None:
      login(request, user)

    next_url = request.POST.get('next')

    if next_url is None: next_url = '/books'

    return redirect(next_url)
  else:
    return render(request, 'books/login.html',
      {'form': LoginForm(), 'next': request.GET.get('next')})

def accountsLogout(request):
  logout(request)
  return redirect('/books')

def accountsSignup(request):
  if request.user.is_authenticated:
    return redirect('/books')

  if request.method == 'POST':
    username = request.POST.get('username')
    email = request.POST.get('email')
    password = request.POST.get('password')

    user = User.objects.create_user(username, email, password)

    try:
      user.save()
    except Exception as e:
      return redirect('/accounts/signup')
    else:
      login(request, user)
      return redirect('/books')
  else:
    return render(request, 'books/signup.html', {'form': SignupForm()})

books/views/activities.py
from django.contrib.contenttypes.models import ContentType
from django.http import JsonResponse
from django.forms.models import model_to_dict

from ..models import Activity

def activities(request):
  user_id = request.POST.get('user_id') or request.user.id

  target_object_type = request.POST.get('target_object_type')
  if target_object_type == 'user':
    target_object_type_id = ContentType.objects.get(
      app_label='auth', model='user').id
  else:
    target_object_type_id = ContentType.objects.get(
      app_label='books', model=target_object_type).id

  target_object_id = request.POST.get('target_object_id')
  content = request.POST.get('content')
  status = request.POST.get('status')
  action_type = request.POST.get('action_type')

  activity = Activity(
    user_id=user_id,
    target_object_id=target_object_id,
    target_object_type_id=target_object_type_id,
    action_type=action_type,
    content=content,
    status=status,
  )
  activity.save()

  return JsonResponse({ **model_to_dict(activity), 'status_text': activity.status_text() })

def activitiesChange(request, pk):
  activity = Activity.objects.get(pk=pk)

  activity.content = request.POST.get('content') or activity.content
  activity.status = request.POST.get('status') or activity.status
  activity.action_type = request.POST.get('action_type') or activity.action_type
  activity.save()

  return JsonResponse({ **model_to_dict(activity), 'status_text': activity.status_text() })

def activitiesDelete(request, pk):
  activity = Activity.objects.get(pk=pk)

  activityChildren = Activity.objects.filter(
    target_object_id=activity.id,
    target_object_type_id=ContentType.objects.get(app_label='books', model='activity').id,
  )

  if activityChildren is not None: activityChildren.delete()

  activity.delete()

  return JsonResponse({})

books/views/books.py
from django.views.generic import ListView, detail
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType

from ..models import Book, Activity
from ..forms import BookListSearchForm

class BookListView(ListView):
  paginate_by = 8
  model = Book
  form_class = BookListSearchForm

  def get_queryset(self):
    filter_params = dict(self.request.GET)
    user_id = filter_params.get('user_id', [None])[0]
    if user_id is None or user_id == '': user_id = self.request.user.id
    activities = Activity.objects.filter(
        user_id=user_id,
        target_object_type_id=ContentType.objects.get(
          app_label='books', model='book').id
      )
    query_or = Q()

    if filter_params.get('reading', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.READ, status=Activity.READING).values('target_object_id'))

    if filter_params.get('readed', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.READ, status=Activity.READED).values('target_object_id'))

    if filter_params.get('favorite', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.FAVORITE).values('target_object_id'))

    if filter_params.get('pending', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.BUY, status=Activity.BUY_PENDING).values('target_object_id'))

    if filter_params.get('approve', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.BUY, status=Activity.BUY_APPROVE).values('target_object_id'))

    if filter_params.get('reject', [None])[0] is not None:
      query_or |= Q(id__in=activities.filter(
        action_type=Activity.BUY, status=Activity.BUY_REJECT).values('target_object_id'))

    query_and = Q()

    for field in ['title__contains', 'pub_date__lt', 'pub_date__gt']:
      field_filter = filter_params.get(field, [None])[0]
      if field_filter: query_and &= Q(**{field: field_filter})

    return Book.objects.filter(Q(query_or) & Q(query_and))

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)

    context['form'] = self.form_class(self.request.GET)
    context['newest_book_public'] = Book.objects.all().order_by('-pub_date')[0]
    context['newest_review'] = Activity.objects.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.COMMENT,)[0]
    context['is_search'] = self.request.GET.get('is_search')
    context['page'] = self.request.GET.get('page')

    return context

class BookDetailView(detail.DetailView):
  model = Book

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)

    user = self.request.user
    book = kwargs['object']

    context['read'] = book.activities().filter(
      user_id=user.id, action_type=Activity.READ).first()
    context['favorite'] = book.activities().filter(
      user_id=user.id, action_type=Activity.FAVORITE).first()
    context['buy'] = book.activities().filter(
      user_id=user.id, action_type=Activity.BUY).first()
    context['rate'] = book.activities().filter(
      user_id=user.id, action_type=Activity.RATE).first()

    return context

books/views/users.py
from django.views.generic import detail
from django.contrib.contenttypes.models import ContentType

from ..models import User, Book, Activity

class UserDetailView(detail.DetailView):
  model = User
  template_name = 'books/user_detail.html'

  def get_context_data(self, **kwargs):
    MAX_EXTRA_RECORD = 3

    context = super().get_context_data(**kwargs)

    current_user = self.request.user
    user = kwargs['object']

    activities = Activity.objects.filter(user_id=user.id)

    context['follow_act'] = Activity.objects.filter(
      user_id=current_user.id,
      target_object_id=user.id,
      target_object_type_id=ContentType.objects.get(
        app_label='auth', model='user').id,
      action_type=Activity.FOLLOW).first()

    following = Activity.objects.filter(
      target_object_id=user.id,
      target_object_type_id=ContentType.objects.get(
        app_label='auth', model='user').id,
      action_type=Activity.FOLLOW)
    context['following_count'] = following.count()
    context['following_users'] = User.objects.filter(
      id__in=[a.user_id for a in following[:MAX_EXTRA_RECORD]])

    followed = Activity.objects.filter(
      user_id=user.id,
      target_object_type_id=ContentType.objects.get(
        app_label='auth', model='user').id,
      action_type=Activity.FOLLOW)
    context['followed_count'] = followed.count()
    context['followed_users'] = User.objects.filter(
      id__in=[a.target_object_id for a in followed[:MAX_EXTRA_RECORD]])

    reading = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.READ,
      status=Activity.READING)

    context['reading_count'] = reading.count()
    context['reading_books'] = Book.objects.filter(
      id__in=[a.target_object_id for a in reading[:MAX_EXTRA_RECORD]])

    readed = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.READ,
      status=Activity.READED)

    context['readed_count'] = readed.count()
    context['readed_books'] = Book.objects.filter(
      id__in=[a.target_object_id for a in readed[:MAX_EXTRA_RECORD]])

    favorite = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.FAVORITE)
    context['favorite_count'] = favorite.count()
    context['favorite_books'] = Book.objects.filter(
      id__in=[a.target_object_id for a in favorite[:MAX_EXTRA_RECORD]])

    review = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.COMMENT)

    context['review_count'] = review.count()
    context['reviews'] = review[:MAX_EXTRA_RECORD]

    context['activities'] = activities.filter(
      action_type__in=[Activity.COMMENT, Activity.READ, Activity.FAVORITE,
        Activity.FOLLOW, Activity.BUY]).exclude(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='activity').id)

    return context

books/templates/books/arrange_right.html
<svg
  width="{{ size }}" height="{{ size }}"" class="svg-inline--fa fa-angle-right fa-w-8"
  aria-hidden="true" focusable="false" data-prefix="fas" data-icon="angle-right"
  role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512" data-fa-i2svg="">
  <path fill="currentColor" d="M224.3 273l-136 136c-9.4 9.4-24.6 9.4-33.9 0l-22.6-22.6c-9.4-9.4-9.4-24.6 0-33.9l96.4-96.4-96.4-96.4c-9.4-9.4-9.4-24.6 0-33.9L54.3 103c9.4-9.4 24.6-9.4 33.9 0l136 136c9.5 9.4 9.5 24.6.1 34z"></path>
</svg>

books/templates/books/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/styles/books/style.css' %}">

<div class="navbar navbar-dark bg-dark shadow-sm app-header col">
  {% if request.user.id is not None %}
    <div class="bg-dark collapse" id="navbarHeader" style="">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">About</h4>
            <p class="text-muted">Django project training 01.</p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <div class="row pl-2">
              <span class="text-white">{% include 'books/user_icon.html' with size=30 %}</span>
              <span></span><h4 class="text-white">{{ request.user }}</h4></span>
            </div>
            <ul class="list-unstyled">
              <li><a href='{% url "user_detail" request.user.id %}' class="text-white text-muted">Profile</a></li>
              <li><a href='{% url "logout" %}' class="text-white text-muted">Logout</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
  <div class="container d-flex justify-content-between">
    <a href='{% url "book_list" %}' class="navbar-brand d-flex align-items-center">
      <strong clickable>Bstore</strong>
    </a>
    {% if request.user.id is not None %}
      <div class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </div>
    {% else %}
      <div class="clickable text-white" onclick=window.location.href='{% url "signup" %}'>Signup</div>
    {% endif %}
  </div>
</div>

<div class="app-body">
  <div class="container">
    {% block page_content %}{% endblock %}
    {% block script %}{% endblock %}
  </div>
</div>

books/templates/books/book_detail.html
{% extends "books/base.html" %}
{% load static %}

{% block page_content %}
  {% csrf_token %}
  <br>
  <div class="row" id="book_detail" data-book-id="{{ object.id }}" data-username="{{ request.user }}">
    {% include 'books/book_detail_info.html' with book=object user=request.user %}
    {% include 'books/book_detail_reviews.html' %}
  </div>
{% endblock %}

{% block script %}
  <script src="{% static '/javascripts/books/book_detail_reviews.js' %}"></script>
  <script src="{% static '/javascripts/books/book_detail_info.js' %}"></script>
{% endblock %}

books/templates/books/book_detail_info.html
<div class="col-md book_info">
  <h1 class="font-weight-bold">{{ book.title }}</h1>
  <br>
  <div class="bg-warning text-white mb-2 p-4 rounded">
    <h6>{{ book.author }}</h6>
    <h6>{{ book.category }}</h6>
    <h6>{{ book.pub_date }}</h6>
    <h6>{{ book.number_of_pages }}pages</h6>
  </div>
  <br>
  <div class="book_info_action row pl-1">
    <div class="read">
      {% if read is None %}
        <h6 class="disactive">Unread</h6>
      {% else %}
        <h6 class="active" data-id="{{ read.id }}" data-status="{{ read.status }}">
          {{ read.status_text }}
        </h6>
      {% endif %}
    </div>
    <div class="favorite">
      {% if favorite is None %}
        <h6 class="disactive">Favorite</h6>
      {% else %}
        <h6 class="active" data-id="{{ favorite.id }}" data-status="{{ favorite.status }}">
          {{ favorite.status_text }}
        </h6>
      {% endif %}
    </div>
    <div class="buy">
      {% if buy is None %}
        <h6 class="disactive">Buy</h6>
      {% else %}
        <h6 class="active" data-id="{{ buy.id }}" data-status="{{ buy.status }}">
          {{ buy.status_text }}
        </h6>
      {% endif %}
    </div>
  </div>
</div>

books/templates/books/book_detail_reviews.html
<div class="col-md book_reviews">
  <div class="form-group">
    <div class="row pr-3">
      <div class="col">
        <input type="text" name="review" class="form-control" placeholder="write some your review">
      </div>
      <div>
        <button class="btn btn-primary" id="review_button">Submit</button>
      </div>
    </div>
  </div>
  <div class="book_review d-none">
    <h6></h6>
    <div class="book_review_detail">
      <h6 class="book_review_content small"></h6>
      <div class="book_review_action row float-right">
        <h6 class="delele">Delele</h6>
        <h6 class="edit">Edit</h6>
        <h6 class="reply">Reply</h6>
      </div>
    </div>
    <div class="book_review_comment_list">
    </div>
  </div>
  <div class="book_review_comment_form d-none">
    <h6></h6>
    <div class="row mr-0">
      <div class="col">
        <input type="text" name="comment" class="form-control">
      </div>
      <div>
        <button class="btn btn-primary submit_comment" type="submit">Send</button>
      </div>
    </div>
  </div>
  <div class="book_review_comment d-none">
    <h6></h6>
    <div class="book_review_comment_detail">
      <h6 class="book_review_comment_content small"></h6>
    </div>
  </div>
  <div class="book_review_list overflow-auto">
    {% for review in object.reviews %}
      <div class="book_review" data-id="{{ review.id }}">
        <h6 class="clickable" onclick=window.location.href='{% url "user_detail" review.user.id %}'>
          {{ review.user }}
        </h6>
        <div class="book_review_detail">
          <h6 class="book_review_content small">"{{ review.content }}"</h6>
          <div class="book_review_action row float-right">
            {% if review.user.id == request.user.id %}
              <h6 class="delele">Delele</h6>
              <h6 class="edit">Edit</h6>
            {% endif %}
            <h6 class="reply">Reply</h6>
          </div>
        </div>
        <div class="book_review_comment_list">
          {% for comment in review.comments %}
            <div class="book_review_comment">
              <h6 class="clickable" onclick=window.location.href='{% url "user_detail" comment.user.id %}'>
                {{ comment.user }}
              </h6>
              <div class="book_review_comment_detail activity-{{ comment.id }}">
                <h6 class="book_review_comment_content small">"{{ comment.content }}"</h6>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>
</div>

books/templates/books/book_icon.html
<svg class="bi bi-book" width="{{ size }}" height="{{ size }}" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3.214 1.072C4.813.752 6.916.71 8.354 2.146A.5.5 0 018.5 2.5v11a.5.5 0 01-.854.354c-.843-.844-2.115-1.059-3.47-.92-1.344.14-2.66.617-3.452 1.013A.5.5 0 010 13.5v-11a.5.5 0 01.276-.447L.5 2.5l-.224-.447.002-.001.004-.002.013-.006a5.017 5.017 0 01.22-.103 12.958 12.958 0 012.7-.869zM1 2.82v9.908c.846-.343 1.944-.672 3.074-.788 1.143-.118 2.387-.023 3.426.56V2.718c-1.063-.929-2.631-.956-4.09-.664A11.958 11.958 0 001 2.82z" clip-rule="evenodd"/>
  <path fill-rule="evenodd" d="M12.786 1.072C11.188.752 9.084.71 7.646 2.146A.5.5 0 007.5 2.5v11a.5.5 0 00.854.354c.843-.844 2.115-1.059 3.47-.92 1.344.14 2.66.617 3.452 1.013A.5.5 0 0016 13.5v-11a.5.5 0 00-.276-.447L15.5 2.5l.224-.447-.002-.001-.004-.002-.013-.006-.047-.023a12.582 12.582 0 00-.799-.34 12.96 12.96 0 00-2.073-.609zM15 2.82v9.908c-.846-.343-1.944-.672-3.074-.788-1.143-.118-2.387-.023-3.426.56V2.718c1.063-.929 2.631-.956 4.09-.664A11.956 11.956 0 0115 2.82z" clip-rule="evenodd"/>
</svg>

books/templates/books/book_list.html
{% extends "books/base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block page_content %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
    $(function() {$('#id_pub_date__gt, #id_pub_date__lt').datepicker({ dateFormat: 'yy-mm-dd' })});
  </script>
  <br>
  {% if is_search is None and page is None %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      </ol>
      <div class="carousel-inner p-3 mb-4 bg-light">
        <div class="carousel-item active">
          <div style="height: 30vh"></div>
          <div class="container">
            <div class="carousel-caption text-center text-dark">
              <h1 class="display-4 font-weight-normal">{{ newest_book_public }}</h1>
              <p class="lead font-weight-normal">Newest book public</p>
              <a class="btn btn-outline-secondary" href='{% url "book_detail" newest_book_public.id %}'>Read it</a>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div style="height: 30vh"></div>
          <div class="container">
            <div class="carousel-caption text-dark">
              <h1 class="display-4 font-weight-normal">{{ newest_review.target_object }}</h1>
              <p>
                <span>Lastest review from </span>
                <span><strong>{{ newest_review.user }}</strong></span>
                <span class="font-italic">"{{ newest_review.content }}"</span>
              </p>
              <a class="btn btn-outline-secondary" href='{% url "book_detail" newest_review.target_object_id %}'>Read it</a>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div style="height: 30vh"></div>
          <div class="container">
            <div class="carousel-caption text-dark">
              <h1 class="display-4 font-weight-normal">Django training course.</h1>
              <p>Make awesome things that matter.</p>
              <a class="btn btn-outline-secondary">Learn it</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}

  <form action="{% url 'book_list' %}" method="get" class="mb-0">
    <div class="row book_list_search_form">
      {% bootstrap_form form %}
      <button class="btn btn-primary">Search</button>
    </div>
  </form>
  {% if page_obj %}
    <div class="row book_list">
      {% for book in page_obj %}
        <div onclick=window.location.href='{% url "book_detail" book.id %}'>
          <div class="col-sm container book clickable" >
            <div>
              <h4>{{ book.title }}</h4>
              {{ book.author.full_name }}
            </div>
            <br>
            <div class="book_extra_info">
              {{ book.pub_date }}
              <br>
              {{ book.number_of_pages }}pages
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <br>
    {% include 'books/pagination.html' %}
  {% endif %}
{% endblock %}

books/templates/books/login.html
{% extends "books/base.html" %}
{% load bootstrap4 %}

{% block page_content %}
  <div class="container">
    <div class="row">
      <div class="col-sm"></div>
      <div class="col-sm">
        <br>
        <h1>Login</h1>
        <form acrion="/accounts/signup" method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% if next is not None %}
            <input type="text" name="next" value="{{ next }}" style="display: none;">
          {% endif %}
          {% buttons %}
            <button type="submit" class="btn btn-primary">
              Submit
            </button>
          {% endbuttons %}
        </form>
      </div>
      <div class="col-sm"></div>
  </div>
{% endblock %}

books/templates/books/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
      <span class="clickable btn btn-primary" onclick="nexPage(1)">&laquo; first</span>
      <span class="clickable btn btn-primary" onclick="nexPage({{ page_obj.previous_page_number }})">previous</span>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
      <span class="clickable btn btn-primary" onclick="nexPage({{ page_obj.next_page_number }})">next</span>
      <span class="clickable btn btn-primary" onclick="nexPage({{ page_obj.paginator.num_pages }})">last &raquo;</span>
    {% endif %}
  </span>
</div>
<script type="text/javascript">
  function nexPage(page) {
    window.location.href = '?' + (window.location.href.split('?')[1] || '').split('&')
      .filter(function(i) {return !(i.startsWith('page'))}).join('&') + '&page=' + page
  }
</script>