books/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
  path('', login_required(views.BookListView.as_view()), name='book_list'),
  path('books/', login_required(views.BookListView.as_view()), name='book_list'),
  path('books/<int:pk>/', login_required(views.BookDetailView.as_view()), name='book_detail'),
  path('activities/', login_required(views.activities)),
  path('activities/<int:pk>/change/', login_required(views.activitiesChange)),
  path('activities/<int:pk>/delete/', login_required(views.activitiesDelete)),
  path('users/<int:pk>/', login_required(views.UserDetailView.as_view()), name="user_detail"),
  path('accounts/login/', views.accountsLogin),
  path('accounts/logout/', views.accountsLogout, name='logout'),
  path('accounts/signup/', views.accountsSignup, name='signup'),
]

components/books/urls.py
from django.urls import path

from .views import (
    CategoryCreateView,
    CategoryIndexView,
    CategoryUpdateView,
    CategoryDeleteView,
    BookCreateView,
    BookUpdateReadStatusView,
    BookToggleFavoriteView,
    BookIndexView,
    BookUpdateView,
    BookDeleteView,
    BookDetailView,
    CommentCreateView,
    ReviewCreateView
)

app_name = 'book'

urlpatterns = [
    path('category/create', CategoryCreateView.as_view(), name='category_create'),
    path('category', CategoryIndexView.as_view(), name='category_index'),
    path('category/<int:id>/edit', CategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:id>/del', CategoryDeleteView.as_view(), name='category_delete'),
    path('book/create', BookCreateView.as_view(), name='book_create'),
    path('book', BookIndexView.as_view(), name='book_index'),
    path('book/<int:id>/update-read-status', BookUpdateReadStatusView.as_view(), name='book_update_read_status'),
    path('book/<int:id>/toggle-favorite', BookToggleFavoriteView.as_view(), name='book_toggle_favorite'),
    path('book/<int:id>/edit', BookUpdateView.as_view(), name='book_update'),
    path('book/<int:id>/del', BookDeleteView.as_view(), name='book_delete'),
    path('book/<int:id>/detail', BookDetailView.as_view(), name='book_detail'),
    path('book/<int:id>/create-comment', CommentCreateView.as_view(), name='book_create_comment'),
    path('book/<int:id>/create-review', ReviewCreateView.as_view(), name='book_create_review'),
]

components/users/urls.py
from django.urls import path

from .views import (
    UserLoginView,
    UserRegisterView,
    UserLogoutView,
    UserTimelineView,
    UserMyProfileView,
    MemberIndexView,
    MemberToggleFollowView,
    RequestCreateView,
    MyRequestView,
    RequestUpdateView,
    RequestDeleteView,
    RequestIndexView,
    RequestChangeStatusView
)

app_name = 'user'

urlpatterns = [
    path('login', UserLoginView.as_view(), name='login'),
    path('register', UserRegisterView.as_view(), name='register'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('', UserTimelineView.as_view(), name='timeline'),
    path('my-profile', UserMyProfileView.as_view(), name='my_profile'),
    path('member', MemberIndexView.as_view(), name='member_index'),
    path('member/<int:following_id>/toggle-follow', MemberToggleFollowView.as_view(), name='member_toggle_follow'),
    path('request/create', RequestCreateView.as_view(), name='request_create'),
    path('request/my-request', MyRequestView.as_view(), name='my_request'),
    path('request/<int:id>/edit', RequestUpdateView.as_view(), name='request_update'),
    path('request/<int:id>/del', RequestDeleteView.as_view(), name='request_delete'),
    path('request/', RequestIndexView.as_view(), name='request_index'),
    path('request/<int:id>/change-status', RequestChangeStatusView.as_view(), name='request_change_status'),
]

dpt01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('books.urls')),
    path('admin/', admin.site.urls),
]

pinky_book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('components.users.urls')),
    path('', include('components.books.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('signin/', Login.as_view(), name='signin'),
    path('signout/', Logout.as_view(), name='signout'),
    path('signup/', Register.as_view(), name='signup'),
]

books/views/users.py
from django.views.generic import detail
from django.contrib.contenttypes.models import ContentType

from ..models import User, Book, Activity

class UserDetailView(detail.DetailView):
  model = User
  template_name = 'books/user_detail.html'

  def get_context_data(self, **kwargs):
    MAX_EXTRA_RECORD = 3

    context = super().get_context_data(**kwargs)

    current_user = self.request.user
    user = kwargs['object']

    activities = Activity.objects.filter(user_id=user.id)

    context['follow_act'] = Activity.objects.filter(
      user_id=current_user.id,
      target_object_id=user.id,
      target_object_type_id=ContentType.objects.get(
        app_label='auth', model='user').id,
      action_type=Activity.FOLLOW).first()

    following = Activity.objects.filter(
      target_object_id=user.id,
      target_object_type_id=ContentType.objects.get(
        app_label='auth', model='user').id,
      action_type=Activity.FOLLOW)
    context['following_count'] = following.count()
    context['following_users'] = User.objects.filter(
      id__in=[a.user_id for a in following[:MAX_EXTRA_RECORD]])

    followed = Activity.objects.filter(
      user_id=user.id,
      target_object_type_id=ContentType.objects.get(
        app_label='auth', model='user').id,
      action_type=Activity.FOLLOW)
    context['followed_count'] = followed.count()
    context['followed_users'] = User.objects.filter(
      id__in=[a.target_object_id for a in followed[:MAX_EXTRA_RECORD]])

    reading = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.READ,
      status=Activity.READING)

    context['reading_count'] = reading.count()
    context['reading_books'] = Book.objects.filter(
      id__in=[a.target_object_id for a in reading[:MAX_EXTRA_RECORD]])

    readed = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.READ,
      status=Activity.READED)

    context['readed_count'] = readed.count()
    context['readed_books'] = Book.objects.filter(
      id__in=[a.target_object_id for a in readed[:MAX_EXTRA_RECORD]])

    favorite = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.FAVORITE)
    context['favorite_count'] = favorite.count()
    context['favorite_books'] = Book.objects.filter(
      id__in=[a.target_object_id for a in favorite[:MAX_EXTRA_RECORD]])

    review = activities.filter(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='book').id,
      action_type=Activity.COMMENT)

    context['review_count'] = review.count()
    context['reviews'] = review[:MAX_EXTRA_RECORD]

    context['activities'] = activities.filter(
      action_type__in=[Activity.COMMENT, Activity.READ, Activity.FAVORITE,
        Activity.FOLLOW, Activity.BUY]).exclude(
      target_object_type_id=ContentType.objects.get(
        app_label='books', model='activity').id)

    return context

components/users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from .forms import (
    RegisterForm,
    LoginForm,
    PasswordChangeForm,
    RequestCreateForm,
    RequestUpdateForm
)
from .models import (
    User,
    Request,
    Follow
)
from .decorators import admin_required


class UserRegisterView(View):
    template_name = 'register.html'

    def get(self, request, *args, **kwargs):
        logout(request)

        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        register_form = RegisterForm(request.POST)

        if register_form.is_valid():
            user = register_form.save()
            login(request, user)

            return redirect(reverse('user:timeline'))

        return render(request, self.template_name, {'form': register_form})


class UserLogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)

        return redirect(reverse('user:login'))


class UserLoginView(View):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        logout(request)

        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user = authenticate(username=login_form.cleaned_data['email'], password=login_form.cleaned_data['password'])
            login(request, user)

            return redirect(reverse('user:timeline'))

        return render(request, self.template_name, {'form': login_form})


class UserTimelineView(View):
    template_name = 'timeline.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class UserMyProfileView(View):
    template_name = 'my_profile.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        password_change_form = PasswordChangeForm(request.user, request.POST)

        if password_change_form.is_valid():
            user = password_change_form.save()
            login(request, user)

            messages.success(request, 'Thay đổi mật khẩu thành công')

            return redirect(reverse('user:my_profile'))

        return render(request, self.template_name, {'form': password_change_form})


class MemberIndexView(View):
    template_name = 'member_index.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        status_title = {
            0: 'không theo dõi',
            1: 'đang theo dõi'
        }
        roles = {
            1: 'Quản trị viên',
            2: 'Thành viên'
        }
        status = {
            0: 'Theo dõi',
            1: 'Đang theo dõi'
        }
        icon_class = {
            0: 'fa fa-rss',
            1: 'fa fa-check'
        }
        title = 'Tất cả thành viên'
        having = ''

        if request.GET.get('user_id'):
            user_id = int(request.GET.get('user_id'))
            username = get_object_or_404(User, pk=user_id).username
        else:
            user_id = request.user.id
            username = request.user.username
        if request.GET.get('following'):
            following = int(request.GET.get('following'))
            having += f"AND is_following={following} "
            title = f"Danh sách thành viên {username} {status_title[following]}"
        if request.GET.get('follower'):
            follower = int(request.GET.get('follower'))
            having = f"AND is_follower={follower} "
            title = f"Danh sách thành viên {status_title[follower]} {username}"

        user_column = "user.id,user.password,user.username,user.email,user.role"

        sql = f"SELECT {user_column}," \
              "IF(following.id, 1, 0) is_following," \
              "IF(follower.id, 1, 0) is_follower " \
              "FROM user " \
              "LEFT JOIN follow AS following " \
              f"ON user.id = following.following_id AND following.follower_id = {user_id} " \
              "LEFT JOIN follow AS follower " \
              f"ON user.id = follower.follower_id AND follower.following_id = {user_id} " \
              f"GROUP BY {user_column}," \
              "following.id," \
              "follower.id " \
              f"HAVING user.id IS NOT NULL {having} " \
              "ORDER BY user.role"

        members = User.objects.raw(sql)

        return render(request, self.template_name, {
            'members': members,
            'roles': roles,
            'title': title,
            'status': status,
            'icon_class': icon_class
        })


class MemberToggleFollowView(View):
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        following_id = kwargs.get('following_id')
        follow = Follow.objects.filter(follower=request.user, following_id=following_id).first()

        if follow:
            follow.delete()
        else:
            if following_id == request.user.id:
                return HttpResponseForbidden('403 Forbidden')

            Follow.objects.create(follower=request.user, following_id=following_id)

        return HttpResponse('delete' if follow else 'create')


class RequestCreateView(View):
    template_name = 'request_create.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        request_create_form = RequestCreateForm(request.user, request.POST)
        if request_create_form.is_valid():
            request_create_form.save()

            messages.success(request, 'Thêm mới yêu cầu thành công')

            return redirect(reverse('user:my_request'))

        return render(request, self.template_name, {'form': request_create_form})


class MyRequestView(View):
    template_name = 'my_request.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        status = {
            1: 'Chờ duyệt',
            2: 'Phê duyệt',
            3: 'Hoàn thành'
        }

        my_request = Request.objects.filter(user=request.user).all()

        return render(request, self.template_name, {'my_request': my_request, 'status': status})


class RequestUpdateView(View):
    template_name = 'request_update.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        request_id = kwargs.get('id')
        request_object = get_object_or_404(Request, pk=request_id)

        if request_object.status != 1:
            messages.error(request, 'Yêu cầu đã được phê duyệt bạn không thể chỉnh sửa')
            return redirect(reverse('user:my_request'))

        return render(request, self.template_name, {'request_object': request_object})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        request_id = kwargs.get('id')
        request_object = get_object_or_404(Request, pk=request_id)
        request_update_form = RequestUpdateForm(request.POST, instance=request_object)

        if request_update_form.is_valid():
            if request_object.status != 1:
                messages.error(request, 'Yêu cầu đã được phê duyệt bạn không thể chỉnh sửa')
            else:
                request_update_form.save()
                messages.success(request, 'Cập nhật yêu cầu thành công')

            return redirect(reverse('user:my_request'))

        return render(request, self.template_name, {'request_object': request_object, 'form': request_update_form})


class RequestDeleteView(View):
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        request_id = kwargs.get('id')
        request_object = get_object_or_404(Request, pk=request_id)

        if (request.user.role == 2) and (request_object.status != 1):
            return HttpResponseForbidden('Yêu cầu đã được phê duyệt bạn không thể xoá')

        if (request.user.role == 1) and (request_object.status == 3):
            return HttpResponseForbidden('Yêu cầu đã được hoàn thành bạn không thể xoá')

        request_object.delete()

        return HttpResponse('ok')


class RequestIndexView(View):
    template_name = 'request_index.html'

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        status = {
            1: 'Chờ duyệt',
            2: 'Phê duyệt',
            3: 'Hoàn thành'
        }

        requests = Request.objects.prefetch_related('user').order_by('-id').all()

        return render(request, self.template_name, {'requests': requests, 'status': status})


class RequestChangeStatusView(View):
    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        request_id = kwargs.get('id')
        status = int(request.POST.get('status'))

        request_object = get_object_or_404(Request, pk=request_id)

        if request_object.status == 3:
            return HttpResponseForbidden('Yêu cầu đã được hoàn thành bạn không thể cập nhật')

        request_object.status = status
        request_object.save()

        return HttpResponse('ok')

components/users/templates/member_index.html
{% extends 'layouts/master.html' %}
{% load static %}
{% load user_extras %}

{% block content %}
  <div class="page-content-wrapper">
    <div class="page-content">
      <div class="page-bar">
        <ul class="page-breadcrumb">
          <li>
            <a href="javascript:void(0)">Thành viên</a>
            <i class="fa fa-angle-right"></i>
          </li>
          <li>
            <a href="javascript:void(0)">Danh sách</a>
          </li>
        </ul>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% include 'partials/alert_message.html' %}
          <div class="portlet box green-haze">
            <div class="portlet-title">
              <div class="caption">
                {{ title }}
              </div>
            </div>
            <div class="portlet-body">
              <table class="table table-striped table-bordered table-hover" id="sample_1">
                <thead>
                <tr>
                  <th>Hình ảnh</th>
                  <th>Tên</th>
                  <th>Email</th>
                  <th>Vai trò</th>
                  <th>Trạng thái</th>
                  <th>Hành động</th>
                </tr>
                </thead>
                <tbody>
                {% for member in members %}
                  <tr class="{% if member.id == user.id %} member-are-me {% endif %}">
                    <td class="fashion-fix-image-product">
                        <img src="{% static 'img/avatar-no.png' %}" class="img-responsive">
                    </td>
                    <td>{{ member.username }}</td>
                    <td>{{ member.email }}</td>
                    <td>{{ roles|get_item_dictionary:member.role }}</td>
                    <td class="text-center">
                      <span class="hide">{{ member.is_following }}</span>
                      {% if member.id != user.id %}
                        <span class="btn btn-sm default">
                          <i
                            class="fashion-toggle {{ icon_class|get_item_dictionary:member.is_following }}"
                            data-url="{% url 'user:member_toggle_follow' following_id=member.id %}"
                            data-screen="member_index"
                            data-icon-class-create="{{ icon_class.1 }}"
                            data-icon-class-delete="{{ icon_class.0 }}"
                            data-message-create="Bạn đã theo dõi {{ member.username }}"
                            data-message-delete="Bạn đã bõ theo dõi {{ member.username }}"
                          >&nbsp;{{ status|get_item_dictionary:member.is_following }}
                          </i>
                        </span>
                      {% else %}
                        <i class="fa fa-eye"></i>&nbsp;<i class="fa fa-eye"></i>
                      {% endif %}
                    </td>
                    <td>
                      <a href="{% url 'book:book_index' %}?filter_sidebar=1&favorite=1&user_id={{ member.id }}" class="btn default btn-xs red">
                        <i class="fa fa-book"></i>
                        Sách yêu thích
                      </a>
                      <a href="{% url 'book:book_index' %}?filter_sidebar=1&read_status=1&user_id={{ member.id }}" class="btn default btn-xs green">
                        <i class="fa fa-book"></i>
                        Sách đang đọc
                      </a>
                      <a href="{% url 'book:book_index' %}?filter_sidebar=1&read_status=2&user_id={{ member.id }}" class="btn default btn-xs blue">
                        <i class="fa fa-book"></i>
                        Sách đã đọc
                      </a>
                      <a href="{% url 'user:member_index' %}?filter_sidebar=1&following=1&user_id={{ member.id }}" class="btn default btn-xs yellow">
                        <i class="icon-users"></i>
                        Đang theo dõi
                      </a>
                      <a href="{% url 'user:member_index' %}?filter_sidebar=1&follower=1&user_id={{ member.id }}" class="btn default btn-xs purple">
                        <i class="icon-users"></i>
                        Người theo dõi
                      </a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
      jQuery(document).ready(function () {
          TableAdvanced.init();
      });
  </script>
{% endblock %}

components/users/templates/my_request.html
{% extends 'layouts/master.html' %}
{% load static %}
{% load user_extras %}

{% block content %}
  <div class="page-content-wrapper">
    <div class="page-content">
      <div class="page-bar">
        <ul class="page-breadcrumb">
          <li>
            <a href="javascript:void(0)">Quản lý yêu cầu</a>
            <i class="fa fa-angle-right"></i>
          </li>
          <li>
            <a href="javascript:void(0)">Yêu cầu của tôi</a>
          </li>
        </ul>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% include 'partials/alert_message.html' %}
          <div class="portlet box green-haze">
            <div class="portlet-title">
              <div class="caption">
                Yêu cầu của tôi
              </div>
              <div class="actions">
                {% if user.role == 1 %}
                  <a href="{% url 'user:request_create' %}" id="sample_editable_1_new" class="btn green">
                    <i class="fa fa-plus"></i>
                    Thêm mới
                  </a>
                {% endif %}
              </div>
            </div>
            <div class="portlet-body">
              <table class="table table-striped table-bordered table-hover" id="sample_1">
                <thead>
                <tr>
                  <th>STT</th>
                  <th>Nội dung</th>
                  <th>Trạng thái</th>
                  <th>Thời gian tạo</th>
                  <th>Hành động</th>
                </tr>
                </thead>
                <tbody>
                {% for request_object in my_request %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ request_object.content }}</td>
                    <td>{{ status|get_item_dictionary:request_object.status }}</td>
                    <td>{{ request_object.created_at|date:'Y-m-d' }}</td>
                    <td>
                      <a href="{% url 'user:request_update' id=request_object.id %}" class="btn default btn-xs purple {% if request_object.status != 1 %}disabled{% endif %}">
                        <i class="fa fa-edit"></i>
                        Sửa
                      </a>
                      <span
                        data-url="{% url 'user:request_delete' id=request_object.id %}"
                        data-message="Xoá thành công"
                        class="btn default btn-xs black fashion-soft-delete-item {% if request_object.status != 1 %}disabled{% endif %}"
                        data-original-title="Bạn có chắc không"
                        data-btn-ok-label="Đồng ý"
                        data-btn-cancel-label="Không"
                        data-toggle="confirmation"
                        data-placement="left"
                        data-popout="true"
                        data-singleton="true"
                        data-btn-ok-class="btn-success"
                        data-btn-cancel-class="btn-danger"
                      >
                        <i class="fa fa-trash-o"></i>
                        Xoá
                      </span>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
      jQuery(document).ready(function () {
          TableAdvanced.init();
      });
  </script>
{% endblock %}

components/users/templates/request_index.html
{% extends 'layouts/master.html' %}
{% load static %}
{% load book_extras %}

{% block content %}
  <div class="page-content-wrapper">
    <div class="page-content">
      <div class="page-bar">
        <ul class="page-breadcrumb">
          <li>
            <a href="javascript:void(0)">Quản lý yêu cầu</a>
            <i class="fa fa-angle-right"></i>
          </li>
          <li>
            <a href="javascript:void(0)">Danh sách yêu cầu</a>
          </li>
        </ul>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% include 'partials/alert_message.html' %}
          <div class="portlet box green-haze">
            <div class="portlet-title">
              <div class="caption">
                Danh sách yêu cầu
              </div>
              <div class="actions">
                {% if user.role == 1 %}
                  <a href="{% url 'user:request_create' %}" id="sample_editable_1_new" class="btn green">
                    <i class="fa fa-plus"></i>
                    Thêm mới
                  </a>
                {% endif %}
              </div>
            </div>
            <div class="portlet-body">
              <table class="table table-striped table-bordered table-hover" id="sample_1">
                <thead>
                <tr>
                  <th>STT</th>
                  <th>Người tạo</th>
                  <th>Nội dung</th>
                  <th>Trạng thái</th>
                  <th>Thời gian tạo</th>
                  <th>Hành động</th>
                </tr>
                </thead>
                <tbody>
                {% for request_object in requests %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ request_object.user.username }}</td>
                    <td>{{ request_object.content }}</td>
                    <td>
                      <span class="hide">{{ book.read_status }}</span>
                      <select
                        name="read_status"
                        class="form-control bs-select fashion-change-status"
                        data-url="{% url 'user:request_change_status' id=request_object.id %}"
                        data-message="Cập nhật trạng thái thành công"
                        data-screen="request_index"
                        {% if request_object.status == 3 %}disabled{% endif %}
                      >
                        {% for key,item in status.items %}
                          <option value="{{ key }}" {% if request_object.status == key %} selected {% endif %}>{{ item }}</option>
                        {% endfor %}
                      </select>
                    </td>
                    <td>{{ request_object.created_at|date:'Y-m-d' }}</td>
                    <td class="pinky-book-action">
                      <span
                        data-url="{% url 'user:request_delete' id=request_object.id %}"
                        data-message="Xoá thành công"
                        class="btn default btn-xs black fashion-soft-delete-item {% if request_object.status == 3 %}disabled{% endif %}"
                        data-original-title="Bạn có chắc không"
                        data-btn-ok-label="Đồng ý"
                        data-btn-cancel-label="Không"
                        data-toggle="confirmation"
                        data-placement="left"
                        data-popout="true"
                        data-singleton="true"
                        data-btn-ok-class="btn-success"
                        data-btn-cancel-class="btn-danger"
                      >
                        <i class="fa fa-trash-o"></i>
                        Xoá
                      </span>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
      jQuery(document).ready(function () {
          TableAdvanced.init();
      });
  </script>
{% endblock %}